//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEVOLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENEVOLE()
        {
            this.DATEBENEVOLATs = new HashSet<DATEBENEVOLAT>();
        }
    
        public short IDBENEVOLE { get; set; }
        public Nullable<long> NUMEROLICENCE { get; set; }
        public System.DateTime DATENAISSANCE { get; set; }
    
        public virtual PARTICIPANT PARTICIPANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATEBENEVOLAT> DATEBENEVOLATs { get; set; }
    }
}
