//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL()
        {
            this.CONTENUHEBERGEMENTs = new HashSet<CONTENUHEBERGEMENT>();
            this.PROPOSERs = new HashSet<PROPOSER>();
        }
    
        public string CODEHOTEL { get; set; }
        public string NOMHOTEL { get; set; }
        public string ADRESSEHOTEL1 { get; set; }
        public string ADRESSEHOTEL2 { get; set; }
        public string CPHOTEL { get; set; }
        public string VILLEHOTEL { get; set; }
        public string TELHOTEL { get; set; }
        public string MAILHOTEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENUHEBERGEMENT> CONTENUHEBERGEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSER> PROPOSERs { get; set; }
    }
}
