//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENANT
    {
        public short IDINTERVENANT { get; set; }
        public short IDATELIER { get; set; }
        public string IDSTATUT { get; set; }
    
        public virtual ATELIER ATELIER { get; set; }
        public virtual PARTICIPANT PARTICIPANT { get; set; }
        public virtual STATUT STATUT { get; set; }
    }
}
