//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        public short ID { get; set; }
        public short IDLICENCIE { get; set; }
        public decimal MONTANTCHEQUE { get; set; }
        public int NUMEROCHEQUE { get; set; }
        public string TYPEPAIEMENT { get; set; }
    
        public virtual LICENCIE LICENCIE { get; set; }
    }
}
