//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRE
    {
        public string NOMDDL { get; set; }
        public string ADRUE1 { get; set; }
        public string ADRUE2 { get; set; }
        public string CP { get; set; }
        public string VILLE { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string MAIL { get; set; }
        public decimal TARIFINSCRIPTION { get; set; }
        public decimal TARIFREPASACCOMPAGNANT { get; set; }
        public decimal DUREE { get; set; }
        public decimal NBATELIERMAX { get; set; }
    }
}
