//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPER
    {
        public short IDLICENCIE { get; set; }
        public short IDATELIER { get; set; }
        public bool NUMERO { get; set; }
    
        public virtual INSCRIRE INSCRIRE { get; set; }
        public virtual VACATION VACATION { get; set; }
    }
}
