//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkM2L
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSER
    {
        public string CODEHOTEL { get; set; }
        public string IDCATEGORIE { get; set; }
        public decimal TARIFNUITE { get; set; }
    
        public virtual CATEGORIECHAMBRE CATEGORIECHAMBRE { get; set; }
        public virtual HOTEL HOTEL { get; set; }
    }
}
